sudo: required
matrix:
  include:
    - python: "3.8"
      dist: xenial
      sudo: true
install:
    - pip install -r requirement.txt
    - pip install pytest coveralls
script: PYTHONPATH=. py.test --cov=open_weather_api test/
after_success: coveralls
