sudo: required
language: python
python:
  - "3.8"
install:
    - pip install -r requirements.txt
    - pip install pytest coveralls
script: PYTHONPATH=. py.test --cov=open_weather_api test/
after_success: coveralls
